openapi: 3.0.3
info:
  description: "Добавление, чтение, обновление и удаление информации о кандидатах\
    \ в стажёры и стажировках"
  title: Сервис стажёров
  version: "1.0"
servers:
- url: https://localhost:8080/api/v1
tags:
- name: Candidates
- name: Internships
paths:
  /candidates:
    get:
      operationId: get_candidates
      parameters:
      - explode: true
        in: query
        name: candidateName
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidatePhone
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidateEmail
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidateSkills
        required: false
        schema:
          example: []
          items:
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: candidatePosition
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidateHoursMin
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: candidateHoursMax
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: candidateEmploymentType
        required: false
        schema:
          type: string
        style: form
      - description: Количество кандидатов на одной странице
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "Количество кандидатов, которые следует пропустить перед возв\
          ращением результатов"
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          minimum: 0
          type: integer
        style: form
      - description: Поле по которому сортировать
        explode: true
        in: query
        name: sortBy
        required: false
        schema:
          example: name
          type: string
        style: form
      - description: "Порядок сортировки (asc - порядок возрастания для чисел, алф\
          авитный порядок для строк, dsc - наоборот)"
        explode: true
        in: query
        name: sortOrder
        required: false
        schema:
          enum:
          - asc
          - dsc
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCandidates_200_response'
          description: successful operation
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error (если сервер не может обработать запрос)
      summary: Получить список всех кандидатов в стажёры
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
    post:
      operationId: add_candidate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Candidate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateWithId'
          description: successful operation
        "400":
          description: Bad request
        "409":
          description: Candidate already exists (если кандидат с такими данными уже
            существует)
      summary: Добавить кандидата в стажёры
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
  /candidates/external:
    get:
      operationId: export_candidates
      parameters:
      - explode: true
        in: query
        name: candidateName
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidatePhone
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidateEmail
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidateSkills
        required: false
        schema:
          example: []
          items:
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: candidatePosition
        required: false
        schema:
          example: ""
          type: string
        style: form
      - explode: true
        in: query
        name: candidateHours
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: candidateEmploymentType
        required: false
        schema:
          type: string
        style: form
      - description: Количество кандидатов на одной странице
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "Количество кандидатов, которые следует пропустить перед возв\
          ращением результатов"
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          minimum: 0
          type: integer
        style: form
      - description: Поле по которому сортировать
        explode: true
        in: query
        name: sortBy
        required: false
        schema:
          example: name
          type: string
        style: form
      - description: "Порядок сортировки (asc - порядок возрастания для чисел, алф\
          авитный порядок для строк, dsc - наоборот)"
        explode: true
        in: query
        name: sortOrder
        required: false
        schema:
          enum:
          - asc
          - dsc
          type: string
        style: form
      responses:
        "200":
          content:
            text/csv:
              schema:
                format: binary
                type: string
          description: Экспортирование завершенно успешно
      summary: Экспортировать таблицу стажёров из базы данных в CSV файл
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
    post:
      operationId: import_candidates
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/importCandidates_request'
      responses:
        "200":
          description: Импортирование завершенно успешно
      summary: Импортировать в базу данных стажёров из CSV файла
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
  /candidates/{candidateID}:
    delete:
      operationId: delete_candidate
      parameters:
      - explode: false
        in: path
        name: candidateID
        required: true
        schema:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "404":
          description: Not found
      summary: Удалить кандидата в стажёры
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
    get:
      operationId: get_candidateby_id
      parameters:
      - explode: false
        in: path
        name: candidateID
        required: true
        schema:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateWithId'
          description: successful operation
        "404":
          description: Candidate not found
        "400":
          description: Bad request
      summary: Получить кандидата в стажеры по ID
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
    put:
      operationId: update_candidate
      parameters:
      - explode: false
        in: path
        name: candidateID
        required: true
        schema:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Candidate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateWithId'
          description: успешно
        "400":
          description: Bad request
        "404":
          description: Not found
      summary: Обновить данные кандидата в стажёры
      tags:
      - Candidates
      x-openapi-router-controller: openapi_server.controllers.candidates_controller
  /internships:
    get:
      operationId: get_internships
      parameters:
      - description: Фильтрация стажировок по должности
        explode: true
        in: query
        name: position
        required: false
        schema:
          example: Junior Backend Developer
          type: string
        style: form
      - description: Максимальное значение часов в неделю
        explode: true
        in: query
        name: hoursMax
        required: false
        schema:
          type: integer
        style: form
      - description: Минимальное значение часов в неделю
        explode: true
        in: query
        name: hoursMin
        required: false
        schema:
          type: integer
        style: form
      - description: Значение статуса
        explode: true
        in: query
        name: status
        required: false
        schema:
          type: string
        style: form
      - description: Фильтрация стажировок по департаменту
        explode: true
        in: query
        name: department
        required: false
        schema:
          example: ДРВПО
          type: string
        style: form
      - explode: true
        in: query
        name: skills
        required: false
        schema:
          example: []
          items:
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: employmentType
        required: false
        schema:
          type: string
        style: form
      - description: Количество стажировок на одной странице
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "Количество стажировок, которые следует пропустить перед возв\
          ращением результатов"
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          minimum: 0
          type: integer
        style: form
      - description: Поле по которому сортировать
        explode: true
        in: query
        name: sortBy
        required: false
        schema:
          example: name
          type: string
        style: form
      - description: "Порядок сортировки (asc - порядок возрастания для чисел, алф\
          авитный порядок для строк, dsc - наоборот)"
        explode: true
        in: query
        name: sortOrder
        required: false
        schema:
          enum:
          - asc
          - dsc
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getInternships_200_response'
          description: Successful operation
        "400":
          description: Error
      summary: Получить список всех стажировок
      tags:
      - Internships
      x-openapi-router-controller: openapi_server.controllers.internships_controller
    post:
      operationId: add_internship
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Internship'
                - type: array
                  items:
                    $ref: '#/components/schemas/Internship'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/InternshipWithId'
                  - type: array
                    items:
                      $ref: '#/components/schemas/InternshipWithId'
          description: Successful operation
        "400":
          description: Bad request
      summary: Добавить запрос на стажёра
      tags:
      - Internships
      x-openapi-router-controller: openapi_server.controllers.internships_controller
  /internships/{internshipId}:
    delete:
      operationId: delete_internship
      parameters:
      - explode: false
        in: path
        name: internshipId
        required: true
        schema:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
        "404":
          description: Not found
      summary: Удалить запрос на стажёра
      tags:
      - Internships
      x-openapi-router-controller: openapi_server.controllers.internships_controller
    get:
      operationId: get_internshipby_id
      parameters:
      - explode: false
        in: path
        name: internshipId
        required: true
        schema:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipWithId'
          description: Successful operation
        "404":
          description: Not found
      summary: Получить стажировку по ID
      tags:
      - Internships
      x-openapi-router-controller: openapi_server.controllers.internships_controller
    put:
      operationId: update_internship
      parameters:
      - explode: false
        in: path
        name: internshipId
        required: true
        schema:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Internship'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipWithId'
          description: Successful operation
        "404":
          description: Not found
      summary: Обновить запрос на стажёра
      tags:
      - Internships
      x-openapi-router-controller: openapi_server.controllers.internships_controller
components:
  schemas:
    CandidateWithId:
      example:
        id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
        body:
          skills: skills
          pathToResume: pathToResume
          education: education
          hoursPerWeek: 21
          phone: "+77777777777"
          employmentType: в офисе
          name: Иванов Иван Иванович
          links: links
          position: position
          experience: experience
          email: example@example.com
      properties:
        id:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          title: id
          type: string
        body:
          $ref: '#/components/schemas/Candidate'
      title: CandidateWithId
      type: object
    Candidate:
      example:
        skills:
          - skill 1
          - skill2
        pathToResume: pathToResume
        education: education
        hoursPerWeek: 21
        phone: "+77777777777"
        employmentType: в офисе
        name: Иванов Иван Иванович
        links: links
        position: position
        experience: experience
        email: example@example.com
      properties:
        name:
          example: Иванов Иван Иванович
          title: name
          type: string
        email:
          example: example@example.com
          format: email
          title: email
          type: string
        phone:
          example: "+77777777777"
          format: phone
          title: phone
          type: string
        position:
          title: position
          type: string
        education:
          title: education
          type: string
        skills:
          title: skills
          type: string
        experience:
          title: experience
          type: string
        hoursPerWeek:
          maximum: 40
          minimum: 20
          title: hoursPerWeek
          type: integer
        employmentType:
#          enum:
#          - в офисе
#          - удалённо
#          - гибрид
          title: employmentType
          type: string
        links:
          title: links
          type: string
        pathToResume:
          title: pathToResume
          type: string
      title: Candidate
      type: object
    InternshipWithId:
      example:
        id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
        body:
          skills: skills
          education: education
          hoursPerWeek: 21
          employmentType: в офисе
          description: description
          position: position
          department: department
          status: просмотрено
      properties:
        id:
          example: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          format: uuid
          title: id
          type: string
        body:
          $ref: '#/components/schemas/Internship'
      title: InternshipWithId
      type: object
    Internship:
      example:
        skills:
          - skill 1
          - skill 2
        education: education
        hoursPerWeek: 21
        employmentType: в офисе
        description: description
        position: position
        department: department
        status: просмотрено
      properties:
        position:
          title: position
          type: string
        education:
          title: education
          type: string
        skills:
          title: skills
          type: string
        department:
          title: department
          type: string
        hoursPerWeek:
          maximum: 40
          minimum: 20
          title: hoursPerWeek
          type: integer
        employmentType:
#          enum:
#          - в офисе
#          - удалённо
#          - гибрид
          title: employmentType
          type: string
        description:
          title: description
          type: string
        status:
          enum:
          - просмотрено
          - отложено
          - заблокировано
          title: status
          type: string
      title: Internship
      type: object
    Pagination:
      example:
        total: 6
        offset: 5
        limit: 1
        remaining: 5
      properties:
        total:
          description: Общее количество стажировок
          title: total
          type: integer
        limit:
          description: Количество стажировок на одной странице
          title: limit
          type: integer
        offset:
          description: Количество пропущенных стажировок
          title: offset
          type: integer
        remaining:
          description: Количество оставшихся стажировок (Общее количество минус количество
            на текущей странице)
          title: remaining
          type: integer
      title: Pagination
      type: object
    getCandidates_200_response:
      example:
        pagination:
          total: 6
          offset: 5
          limit: 1
          remaining: 5
        data:
        - id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          body:
            skills: skills
            pathToResume: pathToResume
            education: education
            hoursPerWeek: 21
            phone: "+77777777777"
            employmentType: в офисе
            name: Иванов Иван Иванович
            links: links
            position: position
            experience: experience
            email: example@example.com
        - id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          body:
            skills: skills
            pathToResume: pathToResume
            education: education
            hoursPerWeek: 21
            phone: "+77777777777"
            employmentType: в офисе
            name: Иванов Иван Иванович
            links: links
            position: position
            experience: experience
            email: example@example.com
      properties:
        data:
          items:
            $ref: '#/components/schemas/CandidateWithId'
          title: data
          type: array
        pagination:
          $ref: '#/components/schemas/Pagination'
      title: getCandidates_200_response
      type: object
    importCandidates_request:
      properties:
        file:
          description: CSV file
          format: binary
          type: string
      type: object
    getInternships_200_response:
      example:
        pagination:
          total: 6
          offset: 5
          limit: 1
          remaining: 5
        data:
        - id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          body:
            skills: skills
            education: education
            hoursPerWeek: 21
            employmentType: в офисе
            description: description
            position: position
            department: department
            status: просмотрено
        - id: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
          body:
            skills: skills
            education: education
            hoursPerWeek: 21
            employmentType: в офисе
            description: description
            position: position
            department: department
            status: просмотрено
      properties:
        data:
          items:
            $ref: '#/components/schemas/InternshipWithId'
          title: data
          type: array
        pagination:
          $ref: '#/components/schemas/Pagination'
      title: getInternships_200_response
      type: object
    addInternship_200_response:
      oneOf:
      - $ref: '#/components/schemas/InternshipWithId'
      - items:
          $ref: '#/components/schemas/InternshipWithId'
        type: array
      title: addInternship_200_response
